# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bootcamp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('inscricao_id', models.AutoField(primary_key=True, serialize=False)),
                ('inscricao_confirmada', models.BooleanField(default=False)),
                ('inscricao_atualizada', models.BooleanField(default=False, editable=False)),
                ('bootcamp', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bootcamp.Bootcamp')),
                ('usuario_inscrito', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Inscrições',
            },
        ),
    ]
