# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 16:18
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeRed_descricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_codered', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Quem Somos',
            },
        ),
        migrations.CreateModel(
            name='Integrante_equipe',
            fields=[
                ('integrante_equipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('integrante_nome', models.CharField(max_length=150)),
                ('integrante_foto', models.FileField(blank=True, null=True, upload_to='static/images')),
                ('integrante_cargo', models.CharField(max_length=150)),
                ('twitter', models.CharField(max_length=150)),
                ('facebook', models.CharField(max_length=150)),
                ('github', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=150)),
                ('ativo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Integrantes',
            },
        ),
    ]
