# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('titulo_evento', models.CharField(max_length=150)),
                ('imagem_evento', models.FileField(blank=True, null=True, upload_to='static/images/')),
                ('legenda_imagem_evento', models.CharField(max_length=150)),
                ('descricao_evento', tinymce.models.HTMLField()),
                ('pre_requisitos_evento', tinymce.models.HTMLField()),
                ('prepare_se_evento', tinymce.models.HTMLField()),
                ('local_evento', tinymce.models.HTMLField()),
                ('carga_horaria_evento', models.IntegerField(default=0)),
                ('data_inicial_evento', models.DateField(default=datetime.date.today)),
                ('data_final_evento', models.DateField(default=datetime.date.today)),
                ('ativo', models.BooleanField(default=False)),
                ('maximo_inscritos', models.IntegerField(default=0)),
                ('inscritos_confirmados', models.IntegerField(default=0)),
                ('inscritos_totais', models.IntegerField(default=0)),
                ('hackathon_id', models.AutoField(primary_key=True, serialize=False)),
                ('proposta_hackathon', tinymce.models.HTMLField()),
                ('equipe', tinymce.models.HTMLField()),
            ],
            options={
                'verbose_name_plural': 'Hackathon',
            },
        ),
    ]
