# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-10 16:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo_codedojo',
            fields=[
                ('artigo_codedojo_id', models.AutoField(primary_key=True, serialize=False)),
                ('em_exibicao', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Artigos CodeDojo',
            },
        ),
        migrations.CreateModel(
            name='Code_dojo',
            fields=[
                ('titulo_evento', models.CharField(max_length=150)),
                ('imagem_evento', models.FileField(blank=True, null=True, upload_to='static/images/')),
                ('legenda_imagem_evento', models.CharField(max_length=150)),
                ('descricao_evento', tinymce.models.HTMLField()),
                ('pre_requisitos_evento', tinymce.models.HTMLField()),
                ('prepare_se_evento', tinymce.models.HTMLField()),
                ('local_evento', tinymce.models.HTMLField()),
                ('carga_horaria_evento', models.IntegerField(default=0)),
                ('data_inicial_evento', models.DateField(default=datetime.date.today)),
                ('data_final_evento', models.DateField(default=datetime.date.today)),
                ('ativo', models.BooleanField(default=False)),
                ('maximo_inscritos', models.IntegerField(default=0)),
                ('inscritos_confirmados', models.IntegerField(default=0)),
                ('inscritos_totais', models.IntegerField(default=0)),
                ('codedojo_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'CodeDojo',
            },
        ),
        migrations.AddField(
            model_name='artigo_codedojo',
            name='code_dojo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='codedojo.Code_dojo'),
        ),
    ]
